### ISSUE TITLE
Create server bin for deployment on external server

### ISSUE THREAD

**Issue by KaymeKaydex** [DominicMaas/Tango#278] opened 2022-07-28 20:06 UTC
There is very slow and busy to create network by smth like hamachi
Lets do the release with binary file to deploy the server on some external pc

**Comment by DominicMaas** [comment] 2022-09-15 20:11
Are you talking about something like #67 ?

**Comment by KaymeKaydex** [comment] 2022-09-15 21:26
> Are you talking about something like #67 ?

yep, there is the same issue

**Comment by DominicMaas** [comment] 2022-09-15 21:36
Cool, I'll close this as a duplicate, feel free to upvote the other issue.

Duplicate of #67

**Closed as not planned by DominicMaas** 2022-09-15 21:36 UTC
Labels: duplicate
